# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/restaurant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/restaurant.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16proto/restaurant.proto\"3\n\x11RestaurantRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\"w\n\x12RestaurantResponse\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.RestaurantResponse.Status\"$\n\x06Status\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\x32\xb8\x01\n\nRestaurant\x12\x36\n\tFoodOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x12\x37\n\nDrinkOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x12\x39\n\x0c\x44\x65ssertOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x62\x06proto3'
)



_RESTAURANTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='RestaurantResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=198,
)
_sym_db.RegisterEnumDescriptor(_RESTAURANTRESPONSE_STATUS)


_RESTAURANTREQUEST = _descriptor.Descriptor(
  name='RestaurantRequest',
  full_name='RestaurantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderID', full_name='RestaurantRequest.orderID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='RestaurantRequest.items', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=77,
)


_RESTAURANTRESPONSE = _descriptor.Descriptor(
  name='RestaurantResponse',
  full_name='RestaurantResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderID', full_name='RestaurantResponse.orderID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='RestaurantResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESTAURANTRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=198,
)

_RESTAURANTRESPONSE.fields_by_name['status'].enum_type = _RESTAURANTRESPONSE_STATUS
_RESTAURANTRESPONSE_STATUS.containing_type = _RESTAURANTRESPONSE
DESCRIPTOR.message_types_by_name['RestaurantRequest'] = _RESTAURANTREQUEST
DESCRIPTOR.message_types_by_name['RestaurantResponse'] = _RESTAURANTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RestaurantRequest = _reflection.GeneratedProtocolMessageType('RestaurantRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESTAURANTREQUEST,
  '__module__' : 'proto.restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantRequest)
  })
_sym_db.RegisterMessage(RestaurantRequest)

RestaurantResponse = _reflection.GeneratedProtocolMessageType('RestaurantResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESTAURANTRESPONSE,
  '__module__' : 'proto.restaurant_pb2'
  # @@protoc_insertion_point(class_scope:RestaurantResponse)
  })
_sym_db.RegisterMessage(RestaurantResponse)



_RESTAURANT = _descriptor.ServiceDescriptor(
  name='Restaurant',
  full_name='Restaurant',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=201,
  serialized_end=385,
  methods=[
  _descriptor.MethodDescriptor(
    name='FoodOrder',
    full_name='Restaurant.FoodOrder',
    index=0,
    containing_service=None,
    input_type=_RESTAURANTREQUEST,
    output_type=_RESTAURANTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DrinkOrder',
    full_name='Restaurant.DrinkOrder',
    index=1,
    containing_service=None,
    input_type=_RESTAURANTREQUEST,
    output_type=_RESTAURANTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DessertOrder',
    full_name='Restaurant.DessertOrder',
    index=2,
    containing_service=None,
    input_type=_RESTAURANTREQUEST,
    output_type=_RESTAURANTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTAURANT)

DESCRIPTOR.services_by_name['Restaurant'] = _RESTAURANT

# @@protoc_insertion_point(module_scope)
