# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import restaurant_pb2 as proto_dot_restaurant__pb2


class RestaurantStub(object):
    """The restaurant service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FoodOrder = channel.unary_unary(
                '/Restaurant/FoodOrder',
                request_serializer=proto_dot_restaurant__pb2.RestaurantRequest.SerializeToString,
                response_deserializer=proto_dot_restaurant__pb2.RestaurantResponse.FromString,
                )
        self.DrinkOrder = channel.unary_unary(
                '/Restaurant/DrinkOrder',
                request_serializer=proto_dot_restaurant__pb2.RestaurantRequest.SerializeToString,
                response_deserializer=proto_dot_restaurant__pb2.RestaurantResponse.FromString,
                )
        self.DessertOrder = channel.unary_unary(
                '/Restaurant/DessertOrder',
                request_serializer=proto_dot_restaurant__pb2.RestaurantRequest.SerializeToString,
                response_deserializer=proto_dot_restaurant__pb2.RestaurantResponse.FromString,
                )


class RestaurantServicer(object):
    """The restaurant service definition.
    """

    def FoodOrder(self, request, context):
        """Sends a order request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrinkOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DessertOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FoodOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.FoodOrder,
                    request_deserializer=proto_dot_restaurant__pb2.RestaurantRequest.FromString,
                    response_serializer=proto_dot_restaurant__pb2.RestaurantResponse.SerializeToString,
            ),
            'DrinkOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DrinkOrder,
                    request_deserializer=proto_dot_restaurant__pb2.RestaurantRequest.FromString,
                    response_serializer=proto_dot_restaurant__pb2.RestaurantResponse.SerializeToString,
            ),
            'DessertOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DessertOrder,
                    request_deserializer=proto_dot_restaurant__pb2.RestaurantRequest.FromString,
                    response_serializer=proto_dot_restaurant__pb2.RestaurantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Restaurant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Restaurant(object):
    """The restaurant service definition.
    """

    @staticmethod
    def FoodOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Restaurant/FoodOrder',
            proto_dot_restaurant__pb2.RestaurantRequest.SerializeToString,
            proto_dot_restaurant__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DrinkOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Restaurant/DrinkOrder',
            proto_dot_restaurant__pb2.RestaurantRequest.SerializeToString,
            proto_dot_restaurant__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DessertOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Restaurant/DessertOrder',
            proto_dot_restaurant__pb2.RestaurantRequest.SerializeToString,
            proto_dot_restaurant__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
